FROM python:3.12-slim-buster

RUN apt-get clean \
  && apt-get -y update

RUN apt-get -y install nginx \
  && apt-get -y install python3-dev \
  && apt-get -y install build-essential

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]