ssh_user: "{{ vault_ssh_user }}"
# ssh_pass: "{{ vault_ssh_pass }}"

docker_network: "proxynet"
tmp_dir: "/tmp"
appdata_dir: "/mnt/user/appdata"

docker_domain: "docker"
server_domain: "{{vault_server_domain}}"

db_host: "{{vault_db_host}}"
db_port: "{{vault_db_port}}"
db_database: "{{vault_db_database}}"
db_user: "{{vault_db_user}}"
db_password: "{{vault_db_password}}"